version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sfn-lambda-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bpc5r3ncke3i"
s3_prefix = "sfn-lambda-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
